sudo: false
language: php
# php:
    # - 5.4
    # - 5.5
    # - 5.6
    # - 7.0
    # - 7.1
    # - 7.2
    # - nightly

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  fast_finish: true
  include:
    - php: 5.4
    - php: 5.5
      env: SENSIO_SECURITY=`true`
    - php: 5.6
      env: PHPUNIT=phpunit-5.7
    - php: 7.0
      env: PHPUNIT=phpunit
    - php: 7.1
      env: PHPUNIT=phpunit
    - php: 7.2
      env: PHPUNIT=phpunit
    - php: nightly
      env: PHPUNIT=phpunit
  allow_failures:
    - php: 5.4
    - php: 5.5 # needs older phpunit
    - php: 7.2
    - php: nightly

before_install:
  - echo $PHPUNIT
  - pwd
  - echo $HOME
  - echo $TRAVIS_PHP_VERSION
  - which composer
  - ls /tmp
  - php --ini
  - if [[ -f /home/travis/.phpenv/versions/$TRAVIS_PHP_VERSION/etc/conf.d/xdebug.ini ]]; then
        cat /home/travis/.phpenv/versions/$TRAVIS_PHP_VERSION/etc/conf.d/xdebug.ini;
        cp /home/travis/.phpenv/versions/$TRAVIS_PHP_VERSION/etc/conf.d/xdebug.ini /tmp;        
        phpenv config-rm xdebug.ini;
    fi
  - install --directory .travis/bin
  # - if [[ $TRAVIS_PHP_VERSION = '7.1'...
  - php .travis/bin/php-cs-fixer self-update || {
        wget http://cs.sensiolabs.org/download/php-cs-fixer-v2.phar --output-document=.travis/bin/php-cs-fixer;
        chmod a+x .travis/bin/php-cs-fixer;
    }
  - '[ -v PHPUNIT ] && wget https://phar.phpunit.de/${PHPUNIT}.phar --output-document=.travis/bin/$PHPUNIT || echo "PHPUnit not downloaded!"'

# - if [[ $TRAVIS_PHP_VERSION != '5.4' && $TRAVIS_PHP_VERSION != '5.5' ]]; then
  #       if [[ $TRAVIS_PHP_VERSION = '5.6' ]]; then
  #           wget https://phar.phpunit.de/phpunit-5.7.phar --output-document=.travis/bin/phpunit;
  #       else
  #           wget https://phar.phpunit.de/phpunit.phar --output-document=.travis/bin/phpunit;
  #       fi;
  #       chmod a+x .travis/bin/phpunit;
  #       PATH=.travis/bin:$PATH;
  #   fi
  - if [[ -v SENSIO_SECURITY ]]; then
        wget http://get.sensiolabs.org/security-checker.phar --output-document=.travis/bin/security-checker;
        # chmod a+x .travis/bin/security-checker;
    fi

install:
  - composer validate
  - composer install --no-scripts --no-progress --no-suggest
  # - cp config/parameters.yml.travis config/parameters.yml
  - composer up --no-progress --no-suggest --optimize-autoloader --apcu-autoloader
  - composer show

before_script:

script:
  - for f in $(find . -path './vendor' -prune -o -path './tests' -prune -o -name \*.php -print) ; do php -l $f ; done # Do this first!
  - if [[ $TRAVIS_PHP_VERSION != '5.4' ]]; then
        for f in $(find ./tests -name \*.php -print) ; do php -l $f ; done;
    fi
  # This checks that the source code follows the Symfony Code Syntax rules:
  - if [[ $TRAVIS_PHP_VERSION = '5.6' || $TRAVIS_PHP_VERSION = '7.0' || $TRAVIS_PHP_VERSION = '7.1' ]]; then 
        .travis/bin/php-cs-fixer --version;
        .travis/bin/php-cs-fixer fix --stop-on-violation --diff --dry-run -vvv --using-cache=no;
    fi
  # - '[ -v PHPUNIT ] && [[ -f /tmp/xdebug.ini ]] && php -c /tmp/xdebug.ini .travis/bin/$PHPUNIT tests || php .travis/bin/$PHPUNIT tests'
  # - '[ -v PHPUNIT ] && { [[ -f /tmp/xdebug.ini ]] && { php -c /tmp/xdebug.ini .travis/bin/$PHPUNIT tests || php .travis/bin/$PHPUNIT tests; } } || echo "PHPUnit not run"'
  -   if [[ -v PHPUNIT ]]; then
          if [[ -f /tmp/xdebug.ini ]]; then
              php --ini -c /tmp/xdebug.ini;
              php -c /tmp/xdebug.ini .travis/bin/$PHPUNIT tests;
          else
              php .travis/bin/$PHPUNIT tests;
          fi;
      else
          echo "PHPUnit not run";
      fi
  # This checks that the application doesn't use dependencies with known security vulnerabilities:
  - if [[ -v SENSIO_SECURITY ]]; then
        php .travis/bin/security-checker security:check --end-point=http://security.sensiolabs.org/check_lock;
    fi
  # - for f in $(find ./vendor -name \*.php) ; do php -l $f > /dev/null ; done # Should be the last line of install but sometimes long to execute and little can be done for errors found.

# inspirated from 
  # symfony/symfony-demo
  # TODO: https://github.com/doctrine/dbal/blob/v2.5.13/.travis.yml
