sudo: false
language: php
php:
    - 5.4
    - 5.5
    # - 5.6
    # - 7.0
    # - 7.1
    - 7.2
    - nightly

cache:
  directories:
    - $HOME/.composer/cache/files

addons:
  # postgresql: "9.6"

services:
  # - postgresql

matrix:
  fast_finish: true
  include:
    - php: 5.6
    - php: 7.0
    - php: 7.1
  allow_failures:
    - php: 5.4
    - php: 5.5 # needs older phpunit
    - php: 7.2
    - php: nightly

before_install:
  - pwd
  - echo $HOME
  - which composer
  - if [ -f /home/travis/.phpenv/versions/$TRAVIS_PHP_VERSION/etc/conf.d/xdebug.ini ]; then phpenv config-rm xdebug.ini; fi
  - composer self-update # May help using cache for php packages.
  - install --directory .travis/bin
  # - if [[ $TRAVIS_PHP_VERSION = '7.1' ]]; then composer require --dev friendsofphp/php-cs-fixer; fi
  - php .travis/bin/php-cs-fixer self-update || {
        wget http://cs.sensiolabs.org/download/php-cs-fixer-v2.phar --output-document=.travis/bin/php-cs-fixer;
        chmod a+x .travis/bin/php-cs-fixer;
    }
  - wget https://phar.phpunit.de/phpunit-5.7.phar --output-document=.travis/bin/phpunit
  - chmod a+x .travis/bin/phpunit
  - if [ $TRAVIS_PHP_VERSION != '5.4' ] || [ '$TRAVIS_PHP_VERSION != '5.5' ]; then
        PATH=.travis/bin/phpunit:$PATH;
    fi

  # - if ! .travis/cache/php$TRAVIS_PHP_VERSION/bin/php-cs-fixer self-update; then
  #     wget http://cs.sensiolabs.org/download/php-cs-fixer-v2.phar -O .travis/cache/php$TRAVIS_PHP_VERSION/bin/php-cs-fixer;
  #     chmod a+x .travis/cache/php$TRAVIS_PHP_VERSION/bin/php-cs-fixer;
  #   fi
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql --dbname=postgres --command='\l'
  - psql --dbname=travis_ci_test --command='\d'
  - psql --host=/var/run/postgresql --dbname=travis_ci_test --command='\d'
  - psql --username=postgres --host=/var/run/postgresql --dbname=travis_ci_test --command='\d'
  # - psql --help

install:
  - composer validate
  - composer install --no-scripts --no-progress --no-suggest
  # - cp config/parameters.yml.travis config/parameters.yml
  - composer up --no-progress --no-suggest --optimize-autoloader --apcu-autoloader
  - composer show
  - phpunit --version
  # - chmod u+x ./bin/console
  # - ./bin/console
  # - ./bin/console dbal:list-databases

before_script:

script:
  - for f in $(find . -path './vendor' -prune -o -name \*.php -print) ; do php -l $f ; done # Do this first!
   # this checks that the source code follows the Symfony Code Syntax rules
  - if [ $TRAVIS_PHP_VERSION = '5.6' ] || [ '$TRAVIS_PHP_VERSION = '7.0' ] || [ '$TRAVIS_PHP_VERSION = '7.1' ]; then 
        .travis/bin/php-cs-fixer fix --stop-on-violation --diff --dry-run -vvv --using-cache=no;
    fi
  # - if [[ $TRAVIS_PHP_VERSION = '7.1' ]]; then ./vendor/bin/php-cs-fixer fix --stop-on-violation --diff --dry-run -vvv --using-cache=no; fi
  - phpunit --bootstrap vendor/autoload.php tests
  # this checks that the application doesn't use dependencies with known security vulnerabilities
  # - ./bin/console security:check --end-point=http://security.sensiolabs.org/check_lock
  # - for f in $(find ./vendor -name \*.php) ; do php -l $f > /dev/null ; done # Should be the last line of install but sometimes long to execute and little can be done for errors found.

# inspirated from 
  # symfony/symfony-demo
  # TODO: https://github.com/doctrine/dbal/blob/v2.5.13/.travis.yml
