---
sudo: false
language: php

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  fast_finish: true
  include:
    - php: 5.4
    - php: 5.5
    - php: 5.6
      env: PHPUNIT=phpunit-5.7
    - php: 7.0
      env: PHPUNIT=phpunit
    - php: 7.1
      env: PHPUNIT=phpunit
    - php: 7.2
      env: PHPUNIT=phpunit
    - php: nightly
      env: PHPUNIT=phpunit
  allow_failures:
    - php: 5.4
    - php: 5.5 # needs older phpunit
    - php: 7.2
    - php: nightly

before_install:
  - echo $PHPUNIT
  - pwd
  - echo $HOME
  - echo $TRAVIS_PHP_VERSION
  - which composer
  - ls /tmp
  - php --ini
  # - "if [[ -f /home/travis/.phpenv/versions/$TRAVIS_PHP_VERSION/etc/conf.d/xdebug.ini ]]; then
  #       cat /home/travis/.phpenv/versions/$TRAVIS_PHP_VERSION/etc/conf.d/xdebug.ini;
  #       cp /home/travis/.phpenv/versions/$TRAVIS_PHP_VERSION/etc/conf.d/xdebug.ini /tmp;        
  #       phpenv config-rm xdebug.ini;
  #   fi"
  - install --directory .travis/bin
  # - if [[ -v PHP_CS_FIXER ]]; then wget http://cs.sensiolabs.org/download/php-cs-fixer-v2.phar --output-document=.travis/bin/php-cs-fixer; fi
  # - '[ -v PHPUNIT ] && wget https://phar.phpunit.de/${PHPUNIT}.phar --output-document=.travis/bin/$PHPUNIT || echo "PHPUnit not downloaded!"'
  # - if [[ -v SENSIO_SECURITY ]]; then
  #       wget http://get.sensiolabs.org/security-checker.phar --output-document=.travis/bin/security-checker;
  #       # chmod a+x .travis/bin/security-checker;
  #   fi
